

//整个替换
export const INDEX_CHANGE_TODOS = 'INDEX_CHANGE_TODOS'
//添加todos
export const INDEX_ADD_TODOS = 'INDEX_ADD_TODOS'
//删除某行
export const INDEX_DELETE_TODOS = 'INDEX_DELETE_TODOS'
//置顶某行
export const INDEX_TOP_TODOS = 'INDEX_TOP_TODOS'
//更改状态
export const INDEX_CHANGE_TODOS_STATUS = 'INDEX_CHANGE_TODOS_STATUS'
//清楚已完成项
export const INDEX_CHANGE_TODOS_CLEAR_COMPLETED = 'INDEX_CHANGE_TODOS_CLEAR_COMPLETED'
