module.exports = {
    'maxerr': false,
    'raw-ignore-regex': false,
    'attr-bans': [
        'align',
        'background',
        'bgcolor',
        'border',
        'frameborder',
        'longdesc',
        'marginwidth',
        'marginheight',
        'scrolling',
        'style',
        'width'
    ],
    'indent-delta': false,
    'indent-style': 'nonmixed',
    'indent-width': 4,
    'indent-width-cont': false,
    'spec-char-escape': true,
    'text-ignore-regex': false,
    'tag-bans': ['style', 'b', 'i'],
    'tag-close': true,
    'tag-name-lowercase': true,
    'tag-name-match': true,
    'tag-self-close': false,
    'doctype-first': false,
    'doctype-html5': false,
    'attr-name-style': 'dash',
    'attr-name-ignore-regex': false,
    'directive-name-forbidden-regex': false,
    'attr-no-dup': true,
    'attr-no-unsafe-char': true,
    'attr-order': false,
    'attr-quote-style': 'double',
    'attr-req-value': true,
    'attr-new-line': false,
    'attr-validate': false,
    'id-no-dup': true,
    'id-class-no-ad': false,
    'id-class-style': false,
    'class-no-dup': false,
    'class-style': false,
    'id-class-ignore-regex': false,
    'img-req-alt': false,
    'img-req-src': false,
    'html-valid-content-model': true,
    'head-valid-content-model': true,
    'href-style': false,
    'link-req-noopener': true,
    'label-req-for': false,
    'line-end-style': 'lf',
    'line-no-trailing-whitespace': false,
    'line-max-len': false,
    'line-max-len-ignore-regex': false,
    'head-req-title': false,
    'title-no-dup': false,
    'title-max-len': 60,
    'html-req-lang': false,
    'lang-style': 'case',
    'fig-req-figcaption' : false,
    'focusable-tabindex-style' : false,
    'input-radio-req-name': false,
    'input-req-label': false,
    'table-req-caption': false,
    'table-req-header': false,
    'tag-req-attr': false,
    'component-prop-regex': false,
    'component-event-regex': false,
    'component-allow-attr': {},
    'tag-embed-tags': false,
    'template-lang': '',
    'origin-tag-list': [],
    'text-forbid-raw': true
};
