const globalVars = {
  WEEX: ['weex', 'global'],
  WX: ['wx', 'global'],
  BAIDU: ['swan', 'global'],
  ALIPAY: ['my', 'global'],
  QQ: ['qq', 'global'],
  WEB: [
    'postMessage', 'blur', 'focus', 'close', 'frames', 'self',
    'window', 'parent', 'opener', 'top', 'length', 'closed',
    'location', 'document', 'origin', 'name', 'history',
    'locationbar', 'menubar', 'personalbar', 'scrollbars',
    'statusbar', 'toolbar', 'status', 'frameElement', 'navigator',
    'customElements', 'external', 'screen', 'innerWidth',
    'innerHeight', 'scrollX', 'pageXOffset', 'scrollY',
    'pageYOffset', 'screenX', 'screenY', 'outerWidth', 'outerHeight',
    'devicePixelRatio', 'clientInformation', 'screenLeft',
    'screenTop', 'defaultStatus', 'defaultstatus', 'styleMedia',
    'onanimationend', 'onanimationiteration', 'onanimationstart',
    'onsearch', 'ontransitionend', 'onwebkitanimationend',
    'onwebkitanimationiteration', 'onwebkitanimationstart',
    'onwebkittransitionend', 'isSecureContext', 'onabort', 'onblur',
    'oncancel', 'oncanplay', 'oncanplaythrough', 'onchange', 'onclick',
    'onclose', 'oncontextmenu', 'oncuechange', 'ondblclick', 'ondrag',
    'ondragend', 'ondragenter', 'ondragleave', 'ondragover', 'ondragstart',
    'ondrop', 'ondurationchange', 'onemptied', 'onended', 'onerror',
    'onfocus', 'oninput', 'oninvalid', 'onkeydown', 'onkeypress',
    'onkeyup', 'onload', 'onloadeddata', 'onloadedmetadata',
    'onloadstart', 'onmousedown', 'onmouseenter', 'onmouseleave',
    'onmousemove', 'onmouseout', 'onmouseover', 'onmouseup', 'onmousewheel',
    'onpause', 'onplay', 'onplaying', 'onprogress', 'onratechange', 'onreset',
    'onresize', 'onscroll', 'onseeked', 'onseeking', 'onselect', 'onstalled',
    'onsubmit', 'onsuspend', 'ontimeupdate', 'ontoggle', 'onvolumechange',
    'onwaiting', 'onwheel', 'onauxclick', 'ongotpointercapture',
    'onlostpointercapture', 'onpointerdown', 'onpointermove',
    'onpointerup', 'onpointercancel', 'onpointerover', 'onpointerout',
    'onpointerenter', 'onpointerleave', 'onafterprint', 'onbeforeprint',
    'onbeforeunload', 'onhashchange', 'onlanguagechange', 'onmessage',
    'onmessageerror', 'onoffline', 'ononline', 'onpagehide', 'onpageshow',
    'onpopstate', 'onrejectionhandled', 'onstorage', 'onunhandledrejection',
    'onunload', 'performance', 'stop', 'open', 'alert', 'confirm', 'prompt',
    'print', 'requestAnimationFrame', 'cancelAnimationFrame', 'requestIdleCallback',
    'cancelIdleCallback', 'captureEvents', 'releaseEvents', 'getComputedStyle',
    'matchMedia', 'moveTo', 'moveBy', 'resizeTo', 'resizeBy', 'getSelection', 'find',
    'webkitRequestAnimationFrame', 'webkitCancelAnimationFrame', 'fetch',
    'btoa', 'atob', 'createImageBitmap', 'scroll', 'scrollTo', 'scrollBy',
    'onappinstalled', 'onbeforeinstallprompt', 'crypto', 'ondevicemotion',
    'ondeviceorientation', 'ondeviceorientationabsolute', 'indexedDB',
    'webkitStorageInfo', 'sessionStorage', 'localStorage', 'chrome',
    'visualViewport', 'speechSynthesis', 'webkitRequestFileSystem',
    'webkitResolveLocalFileSystemURL', 'openDatabase', 'applicationCache',
    'caches', 'whichAnimationEvent', 'animationendEvent', 'infinity',
    'SETTING', 'AppView', 'ExtensionOptions', 'ExtensionView', 'WebView',
    'iconPath', '_app', '_ZOOM_', 'Feed', 'md5', '$', 'jQuery', 'Search',
    'windmill', 'Lethargy', 'alertTimeOut', 'supportApps', 'lethargyX',
    'lethargyY', 'iView', 'onModuleResLoaded', 'iEditDelete', 'infinityDrag',
    'i', 'array', 'TEMPORARY', 'PERSISTENT', 'addEventListener',
    'removeEventListener', 'dispatchEvent'
  ]
};

module.exports = globalVars;
